" designed for vim 8+
let skip_defaults_vim=1
set nocompatible

" test edit
" test edit 2

" activate line numbers
" disable relative line numbers, remove no to sample it
set number
set relativenumber

" turn info in tray on even if default
set ruler

" Mouse support
set mouse=a

" tabs are the devil
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set smartindent
set smarttab
set autoindent

" easier to see characters when `set paste` is on
set listchars=tab:→\ ,eol:↲,nbsp:␣,space:·,trail:·,extends:⟩,precedes:⟨

" enough for line numbers + gutter within 80 
set textwidth=80 

" more risky, but cleaner
set nobackup
set noswapfile
set nowritebackup

" keep the terminal title updated
set laststatus=0
set icon

" center the cursor always on the screen
set scrolloff=10

" highlight search hits,  \+<cr> to clear 
set hlsearch
set incsearch
set linebreak
map <silent> <leader><cr> :noh<cr>

" avoid most of the 'Hit Enter ...' messages
set shortmess=aoOtI

" prevents truncated yanks, deletes, etc.
set viminfo='20,<1000,s1000

" not a fan of bracket matching or folding
let g:loaded_matchparen=1
set noshowmatch
set foldmethod=manual

" Just the defaults, these are changed per filetype by plugins.
" Most of the utility of all of this has been superceded by the use of
" modern simplified pandoc for capturing knowledge source instead of
" arbitrary raw text files.

set formatoptions-=t   " don't auto-wrap text using text width
set formatoptions+=c   " autowrap comments using textwidth with leader
set formatoptions-=r   " don't auto-insert comment leader on enter in insert
set formatoptions-=o   " don't auto-insert comment leader on o/O in normal
set formatoptions+=q   " allow formatting of comments with gq
set formatoptions-=w   " don't use trailing whitespace for paragraphs
set formatoptions-=a   " disable auto-formatting of paragraph changes
set formatoptions-=n   " don't recognized numbered lists
set formatoptions+=j   " delete comment prefix when joining
set formatoptions-=2   " don't use the indent of second paragraph line
set formatoptions-=v   " don't use broken 'vi-compatible auto-wrapping'
set formatoptions-=b   " don't use broken 'vi-compatible auto-wrapping'
set formatoptions+=l   " long lines not broken in insert mode
set formatoptions+=m   " multi-byte character line break support
set formatoptions+=M   " don't add space before or after multi-byte char
set formatoptions-=B   " don't add space between two multi-byte chars in join 
set formatoptions+=1   " don't break a line after a one-letter word

" requires PLATFORM env variable set (in ~/.bashrc)
if $PLATFORM == 'mac'
  " required for mac delete to work
  set backspace=indent,eol,start
endif

" stop complaints about switching buffer with changes
set hidden

" command history
set history=100

" here because plugins and stuff need it
syntax enable

" faster scrolling
set ttyfast

" allow sensing the filetype
filetype plugin on

" ----- Plug-ins -----
" Install vim-plug if not already installed
" (Yes I know about Vim 8 Plugins. They suck.)
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif

set statusline=

" only load plugins if Plug detected
if filereadable(expand("~/.vim/autoload/plug.vim"))
  call plug#begin('~/.vimplugins')
  Plug 'https://github.com/sainnhe/everforest'
  Plug 'vim-airline/vim-airline'
  Plug 'vim-airline/vim-airline-themes'
  " Plug 'itchyny/lightline.vim'
  " Plug 'albertomontesg/lightline-asyncrun' " Integration of https://github.com/skywind3000/asyncrun.vim
  Plug 'luochen1990/rainbow'
  Plug 'universal-ctags/ctags'
  Plug 'preservim/tagbar'
  Plug 'sainnhe/artify.vim'
  Plug 'rmolin88/pomodoro.vim'
  Plug 'ryanoasis/vim-devicons'
  Plug 'airblade/vim-gitgutter'
  Plug 'luochen1990/rainbow'
  Plug 'junegunn/fzf'
  "Plug 'vim-pandoc/vim-pandoc'
  "Plug 'ervandew/supertab'
  Plug 'tpope/vim-surround'
  "Plug 'sheerun/vim-polyglot'
  "Plug 'rust-lang/rust.vim'
  "Plug 'dense-analysis/ale'
  "Plug 'cespare/vim-toml'
  "Plug 'PProvost/vim-ps1'
  "Plug 'fatih/vim-go'
  call plug#end()
endif

" ----------- Color and Style ---------
if has('termguicolors')
  set termguicolors
endif

" --- Airline ---
let g:airline_extensions = []
let g:airline#extensions#ale#enabled = 1
let g:airline_theme = 'everforest'

" For dark version.
" high contrast for streaming, etc.
set background=dark

" Set contrast.
" This configuration option should be placed before `colorscheme everforest`.
" Available values: 'hard', 'medium'(default), 'soft'
let g:everforest_background = 'hard'

" For better performance
let g:everforest_better_performance = 1
let g:everforest_enable_italic = 0
let g:everforest_disable_italic_comment = 0

let g:everforest_transparent_background = 2
let g:everforest_spell_foreground = 'colored'
let g:everforest_ui_contrast = 'high'

let g:everforest_diagnostic_text_highlight = 0
let g:everforest_diagnostic_line_highlight = 'colored'
let g:everforest_diagnostic_virtual_text = 0

colorscheme everforest
hi Normal guibg=NONE ctermbg=NONE

" ----- Super Tab -----
let g:SuperTabDefaultCompletionType = "<C-X><C-O>"

" --- Fuzzy Finder (fzf) ---
nmap <C-P> :FZF<CR>
"let $FZF_DEFAULT_COMMAND='find . \( -name __pycache__ -o -name .ipynb_checkpoints) -prune -o print'

" ----- Duck Markdown linking -----

" fill in empty markdown links with duck.com search
"autocmd vimleavepre *.md !perl -p -i -e 's,\[([^\]]+?)\]\(\),[\1](https://duck.com/lite?kae=t&q=\1),g' %

" enable omni-completion
set omnifunc=syntaxcomplete#Complete

" force some file names to be specific file type
"au bufnewfile,bufRead *.bash* set ft=sh
"au bufnewfile,bufRead *.profile set filetype=sh
"au bufnewfile,bufRead *.crontab set filetype=crontab
"au bufnewfile,bufRead *ssh/config set filetype=sshconfig
au bufnewfile,bufRead *gitconfig set filetype=gitconfig
"au bufnewfile,bufRead /tmp/psql.edit.* set syntax=sql
au bufnewFile,bufRead *.md set filetype=markdown

" displays all the syntax rules for current position, useful
" when writing vimscript syntax plugins
function! <SID>SynStack()
	if !exists("*synstack")
		return
	endif
  echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunc  

" start at last place you were editing
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" functions keys
map <F1> :set number!<CR> :set relativenumber!<CR>
nmap <F2> :call <SID>SynStack()<CR>
set pastetoggle=<F3>
map <F4> :set list!<CR>
map <F5> :set spell!<CR>
map <F7> :set cursorline!<CR>
map <F8> :TagbarToggle<CR>
map <F12> :set fdm=indent<CR>

" read personal/private vim configuration (keep last to override)
set rtp^=~/.vimpersonal
set rtp^=~/.vimprivate
