#!/bin/bash
test type tmux >/dev/null 2>&1 && echo "TMUX isn't installed. Skipping." && exit 1
ln -sf "$PWD/tmux.conf" "$HOME/.tmux.conf"
ln -sf "$PWD/tmux-plain.conf" "$HOME/.tmux-plain.conf"
ln -sf "$PWD/tmuxline" "$HOME/.tmux/tmuxline"

#ln -sf "$PWD/tmux-live.conf" "$HOME/.tmux-live.conf"
